name: Build docker image
on:
  push:
    path:
      - Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        echo "Build docker image"
        docker build -t clojure-lsp-graalvm .
    - name: login to GitHub package registry
      run: |
        echo "Login to GitHub package registry"
        echo ${GITHUB_TOKEN} | docker login docker.pkg.github.com --username rinx --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.CLOJURE_LSP_GRAALVM_TOKEN }}
    - name: tag and push to GitHub package registry
      run: |
        echo "Push to GitHub package registry"
        docker tag clojure-lsp-graalvm docker.pkg.github.com/rinx/dotfiles/devenv:latest
        docker push docker.pkg.github.com/rinx/clojure-lsp-graalvm/clojure-lsp-graalvm:latest
